site_name: 'Foundations of Privacy (CMU Fall 2021)'
site_url: 'https://foundpriv.github.io/'
site_description: 'Foundations of Privacy (Fall 2021)'
site_author: 'Steven Wu'

theme:
  name: 'material'
  language: 'en'
  logo: 'assets/images/favicon.png'
  favicon: 'assets/images/favicon.png'
  features:
    - navigation.tabs
  palette:
    - scheme: default
      primary: blue grey
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

nav:
  - Home:
    - Syllabus: 'index.md'
  - Schedule:
    - Lectures: 'calendar.md'
  - Assignments:
    - Homework: 'hw.md'
    - Project: 'project.md'
  - Resources:
    - Resources: 'resources.md'